language: go
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libpcap0.8 libpcap0.8-dev
- go install github.com/axw/gocov/gocov@latest
- go install github.com/mattn/goveralls@latest
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
go:
  - 1.5
  - 1.6
  - 1.7
  - tip
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
