language: go
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libpcap0.8 libpcap0.8-dev
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
go:
  - 1.5
  - 1.6
  - tip
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN